# To know more on how to change this file to better review your
# repository you can go to https://docs.ebertapp.io/configuration and see the configuration
# details.
---
styleguide: plataformatec/linters
engines:
  credo:
    enabled: true
  csslint:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  remark-lint:
    enabled: true
  scss-lint:
    enabled: true
  tslint:
    enabled: true
    channel: beta
exclude_paths:
- config
- docs
- priv/repo
- script
- spec
pull_requests:
  comments: false
