#!/usr/bin/env bash

set -e

 # shellcheck disable=SC2154
if [ -n "$phoenix_dir" ]; then
  echo "Error: phoenix_dir variable is not assigned"
  exit 1
fi

# shellcheck disable=SC2154
if [ -n "$phoenix_ex" ]; then
  echo "Error: phoenix_ex variable is not assigned"
  exit 1
fi

cd "$phoenix_dir" || exit 1

npm --prefix ./assets run deploy

mix "${phoenix_ex}.digest"

if mix help "${phoenix_ex}.digest.clean" 1>/dev/null 2>&1; then
  mix "${phoenix_ex}.digest.clean"
fi
