#!/usr/bin/env bash

cd $phoenix_dir

npm --prefix ./assets run deploy

mix "${phoenix_ex}.digest"

if mix help "${phoenix_ex}.digest.clean" 1>/dev/null 2>&1; then
  mix "${phoenix_ex}.digest.clean"
fi
