#!/usr/bin/env bash

set -e

if [ -n "$phoenix_ex" ]; then
  phoenix_ex="phx"
fi

cd "$(dirname "$0")/.."

npm --prefix ./assets run deploy

mix "${phoenix_ex}.digest"

if mix help "${phoenix_ex}.digest.clean" 1>/dev/null 2>&1; then
  mix "${phoenix_ex}.digest.clean"
fi
