#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew bundle check 2>&1 >/dev/null || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi

if [ -f "mix.exs" ]; then
  echo "==> Installing mix dependencies…"
  mix deps.get
fi

if [ -f "assets/package.json" ]; then
  echo "==> Installing npm dependencies…"
  cd assets
  npm install
  cd -
fi
