#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew bundle check >/dev/null 2>&1 || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi

if ! command -v node >/dev/null 2>&1; then
  echo "==> Installing node…"
  version=$(cat .node-version)
  nodenv install "$version"
  nodenv rehash
fi

if [ -f "mix.exs" ]; then
  echo "==> Installing mix dependencies…"
  mix deps.get
fi

if [ -f "assets/package.json" ]; then
  echo "==> Installing npm dependencies…"
  (
    cd assets || exit
    npm install
  )
fi
