#!/bin/sh

set -e

cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x

export MIX_ENV="test"

script/bootstrap

echo "==> Setting up DB…"
mix ecto.ci

echo "==> App is now ready to go!"

if [ -n "$TRAVIS" ]; then
  mix coveralls.travis
else
  mix test
fi
