#!/bin/sh

# script/console: Launch a console for the application. Optionally allow an
#                 environment to be passed in to let the script handle the
#                 specific requirements for connecting to a console for that
#                 environment.
#
# Use: script/console [environment]
#
# * `environment` - Name of the environment in which to launch the console, defaults to local
#                   development

set -e

cd "$(dirname "$0")/.."

if [ -n "$1" ]; then
  # use first argument as an environment name. Use this to decide how to connect
  # to the appropriate console.
  if [ "$1" == "production" ]; then
    heroku run --app atom-tweaks "iex -S mix"
  elif [ "$1" == "staging" ]; then
    heroku run --app atom-tweaks-staging "iex -S mix"
  else
    echo "Sorry, I don't know how to connect to the '$1' environment."
    exit 1
  fi
else
  # no argument provided, so just run the local console in the development
  # environment. Ensure the application is up to date first.
  script/update
  iex -S mix
fi
