#!/bin/sh

# script/publish: Publishes the current version of the application to Heroku

set -e

cd "$(dirname "$0")/.."

script/bootstrap

git push origin master
git push heroku master

version=$(heroku releases --json | jq '.[0].version')
git tag "v$version"
git push --tags origin
