#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

# ensure everything in the app is up to date.
script/update

# Call `mix phx.server` within iex to enable the use of `IEx.pry`
iex -S mix phx.server
