#!/bin/sh

# script/test: Run test suite for application. Optionally pass in a path to an
#              individual test file to run a single test.


set -e

cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x

if [ "$MIX_ENV" = "test"  ] || [ "$CI" = "true" ]; then
  MIX_ENV="test" script/setup
else
  MIX_ENV="test" script/update
fi

echo "==> Checking format…"

mix format --check-formatted

echo "==> Running linter…"

mix credo

echo "==> Running tests…"

if [ -n "$1" ]; then
  # pass arguments to test call. This is useful for calling a single test.
  mix test "$1"
else
  mix test
fi

echo "==> Generate translations…"

mix translate
