#!/bin/sh

# script/translate: Extracts new msgids and merges them into translation files in `priv/gettext`.

set -e

cd "$(dirname "$0")/.."

script/update

echo "==> Generating i18n data files…"
mix translate
